export const safetyTips = [
  { title: "Public Spaces Only", desc: "Always arrange swaps in well-lit, highly populated public areas." },
  { title: "Daylight is Best", desc: "Schedule your trades during daylight hours for maximum visibility." },
  { title: "Bring a Friend", desc: "Never go alone. Bring a trusted friend or family member." },
  { title: "Inspect Electronics", desc: "Always turn on electronic devices and verify battery health before swapping." },
  { title: "Check for Stains", desc: "Inspect clothing in good lighting to spot undisclosed stains or tears." },
  { title: "Verify IMEI", desc: "For phones, dial *#06# to check the IMEI against online databases." },
  { title: "Use In-App Chat", desc: "Keep all communication within SwapSoko to maintain a verifiable record." },
  { title: "Trust Your Gut", desc: "If a deal feels too good to be true, walk away immediately." },
  { title: "Avoid Private Homes", desc: "Never agree to meet at someone's house or apartment." },
  { title: "Share Your Location", desc: "Share your live location with a friend during the meetup." },
  { title: "No Last-Minute Changes", desc: "If the other party changes the location at the last minute, cancel." },
  { title: "Check Seller Reviews", desc: "Review the other user's ratings and past swaps before agreeing." },
  { title: "Beware of Pressure", desc: "Never let anyone rush you during an inspection." },
  { title: "Keep Personal Info Private", desc: "Do not share your home address or financial details." },
  { title: "Test Ports", desc: "Bring a charger or power bank to test charging ports." },
  { title: "Examine Hardware", desc: "Check laptops for missing screws, which might indicate tampering." },
  { title: "Look for Original Accessories", desc: "Ask for original boxes and chargers to verify authenticity." },
  { title: "Check Serial Numbers", desc: "Verify serial numbers on high-end electronics via the manufacturer's website." },
  { title: "Meet Near Security", desc: "Cafes near campus security or police stations are ideal." },
  { title: "Avoid Cash Apps with Strangers", desc: "If adding cash, use secure methods and avoid irreversable transfers until satisfied." },
  { title: "Look Out for Phishing", desc: "Never click external links sent by other users in chat." },
  { title: "Ask Questions", desc: "Ask about the history of the item. Vague answers are a red flag." },
  { title: "Check Expiration Dates", desc: "If swapping sealed goods, verify the expiration or warranty dates." },
  { title: "Smell Test", desc: "For appliances or electronics, check for burning smells." },
  { title: "Water Damage", desc: "Look for red water damage indicators inside phone SIM trays." },
  { title: "Account Locks", desc: "Ensure iCloud or Google accounts are fully removed before swapping phones." },
  { title: "Check for Scratches", desc: "Wipe screens with a cloth to distinguish between smudges and deep scratches." },
  { title: "Test Audio", desc: "Play music or record a voice memo to test speakers and microphones." },
  { title: "Check Camera Lenses", desc: "Open the camera app and look for dust spots or focus issues." },
  { title: "Test Buttons", desc: "Press all physical buttons to ensure they are clicky and responsive." },
  { title: "Verify Storage", desc: "Check the settings to confirm the device storage matches the listing." },
  { title: "Look for Re-sealing", desc: "If an item is claimed as 'New in Box', check if the shrink wrap looks tampered with." },
  { title: "Avoid Remote Swaps", desc: "Do not mail items relying on trust. Swap face-to-face." },
  { title: "Document the Swap", desc: "Take a photo of the item you are receiving right after the swap." },
  { title: "Report Suspicious Activity", desc: "Use the report button if a user violates safety guidelines." },
  { title: "Check Authenticity", desc: "For designer wear, look up guides on how to spot fakes." },
  { title: "Test Wi-Fi and Bluetooth", desc: "Connect to a hotspot to ensure wireless chips work." },
  { title: "No Over-payments", desc: "Beware of scams where they offer to overpay via check and ask for a refund." },
  { title: "Check Display Health", desc: "Use a pure white background to check for screen burn-in." },
  { title: "Stay Alert", desc: "Don't get distracted during the meetup. Keep your eyes on the items." },
  { title: "Confirm Identities", desc: "Ask the person to confirm their SwapSoko username when you meet." },
  { title: "Review Return Policies", desc: "Understand that swaps are final. Inspect thoroughly." },
  { title: "Test Zippers and Pockets", desc: "For bags and jackets, ensure all hardware functions smoothly." },
  { title: "Check for Repairs", desc: "Look for signs of unauthorized third-party repairs on electronics." },
  { title: "Verify Battery Cycles", desc: "On laptops, check the battery cycle count if possible." },
  { title: "Test Game Cartridges", desc: "Bring a console to test game discs or cartridges on the spot." },
  { title: "Listen for Noises", desc: "Hard drives or fans shouldn't make clicking or grinding sounds." },
  { title: "Check Hinges", desc: "Open and close laptops to ensure hinges aren't loose or broken." },
  { title: "Beware of Stolen Goods", desc: "If they are selling multiple new, sealed devices for cheap, be cautious." },
  { title: "Check Footwear Soles", desc: "For shoes, check the tread wear to verify 'lightly used' claims." },
  { title: "Verify Bike Serial", desc: "For bicycles, check the bottom bracket for the serial number." },
  { title: "Test Gears and Brakes", desc: "Take a short test ride in a safe area before swapping a bike." }
];
