import React, { createContext, useContext, useState } from "react";

type Lang = "en" | "sw";

const translations = {
  en: {
    home: "Home",
    swipes: "Swipes",
    post: "Post",
    chat: "Chat",
    profile: "Profile",
    communities: "Soko",
    swapGuru: "Swap Guru",
    swapWishes: "Swishes",
    liveSwaps: "Live Swaps Near You",
    recommended: "Recommended For You",
    popularCommunities: "Popular Soko",
    seeAll: "See all",
    proposeSwap: "Propose Swap",
    skip: "Skip",
    save: "Save",
    wants: "Wants",
    have: "Have",
    need: "Need",
    offering: "Offering",
    verified: "Verified",
    verifiedStudent: "Verified Student",
    completedSwaps: "Completed Swaps",
    acceptanceRate: "Acceptance Rate",
    responseTime: "Response Time",
    trustScore: "Trust Score",
    postItem: "Post Item",
    postWish: "Post Wish",
    nearbySwaps: "Nearby Swaps",
    emergencyNeeds: "Emergency Needs",
    freeStuff: "Free Stuff",
    searchPlaceholder: "Search items, skills or anything...",
    askSwapGuru: "Ask Swap Guru",
    swapGuruDesc: "AI finds you better swaps, faster and smarter.",
    inviteFriend: "Invite a friend",
    inviteDesc: "You both get 50 points!",
    inviteNow: "Invite Now",
    safetyFirst: "Safety First",
    safetyDesc: "Meet in public places. Verify items. Trust the community.",
    safetyTips: "Safety Tips →",
    topTraders: "Top Traders",
    viewLeaderboard: "View Leaderboard",
    recentMessages: "Recent Messages",
    viewAllMessages: "View all messages →",
    yourActivity: "Your Activity",
    listings: "Listings",
    active: "Active",
    swapsInProgress: "Swaps in Progress",
    points: "Points",
    viewAllActivity: "View all activity →",
    youreIn: "You're in",
    changeCampus: "Change Campus",
    exploreNear: "Explore near you",
    within5km: "Within 5 km",
    matchScore: "match",
    cashBridge: "Cash Bridge",
    mpesaTopUp: "M-Pesa Top-Up",
    sendProposal: "Send Proposal",
    counterOffer: "Counter Offer",
    accept: "Accept",
    reject: "Reject",
    cancel: "Cancel",
    confirm: "Confirm",
    submit: "Submit",
    back: "Back",
    next: "Next",
    done: "Done",
    loading: "Loading...",
    noResults: "No results found",
    typeMessage: "Type a message...",
    sendVoiceNote: "Send voice note",
    quickReplies: ["Is this available?", "Can we meet today?", "What's the condition?", "Cash top-up OK?"],
    proposalStatus: {
      draft: "Draft",
      sent: "Sent",
      viewed: "Viewed",
      accepted: "Accepted",
      countered: "Countered",
      rejected: "Rejected",
      completed: "Completed",
      expired: "Expired",
      cancelled: "Cancelled",
    },
    swapGuruPrompts: [
      "What can I get for these textbooks?",
      "Find me a laptop near JKUAT",
      "Best swaps for gaming gear?",
      "Is this trade fair?",
    ],
    multiWaySwap: "Multi-Way Swap",
    chainVisualization: "Swap Chain",
    confirmLeg: "Confirm this leg",
    swapCycle: "Swap Cycle",
    rateSwap: "Rate this Swap",
    itemAccuracy: "Item Accuracy",
    communication: "Communication",
    punctuality: "Punctuality",
    fairness: "Fairness",
    overallRating: "Overall Rating",
    submitReview: "Submit Review",
    reportUser: "Report User",
    savedItems: "Saved Items",
    watchlist: "Watchlist",
    language: "Language",
    english: "English",
    swahili: "Swahili",
    settings: "Settings",
    helpSafety: "Help & Safety",
    logout: "Log Out",
    login: "Log In",
    signup: "Sign Up",
    editProfile: "Edit Profile",
    myListings: "My Listings",
    mySwaps: "My Swaps",
    notifications: "Notifications",
    saved: "Saved",
    inviteFriends: "Invite Friends",
    superTrader: "SuperTrader",
    pts: "pts",
    km: "km",
    min: "min",
    ago: "ago",
    new: "NEW",
    hot: "🔥",
  },
  sw: {
    home: "Nyumbani",
    swipes: "Piga Swipe",
    post: "Chapisha",
    chat: "Mazungumzo",
    profile: "Wasifu",
    communities: "Soko",
    swapGuru: "Swap Guru",
    swapWishes: "Swishes",
    liveSwaps: "Ubadilishanaji Karibu Nawe",
    recommended: "Iliyopendekezwa Kwako",
    popularCommunities: "Soko Maarufu",
    seeAll: "Ona zote",
    proposeSwap: "Pendekeza Kubadilishana",
    skip: "Ruka",
    save: "Hifadhi",
    wants: "Anataka",
    have: "Ana",
    need: "Anahitaji",
    offering: "Anatoa",
    verified: "Imethibitishwa",
    verifiedStudent: "Mwanafunzi Aliyethibitishwa",
    completedSwaps: "Ubadilishanaji Uliokamilika",
    acceptanceRate: "Kiwango cha Kukubali",
    responseTime: "Muda wa Kujibu",
    trustScore: "Alama ya Uaminifu",
    postItem: "Chapisha Kitu",
    postWish: "Chapisha Tamaa",
    nearbySwaps: "Ubadilishanaji Karibu",
    emergencyNeeds: "Mahitaji ya Dharura",
    freeStuff: "Vitu Bure",
    searchPlaceholder: "Tafuta vitu, ujuzi au chochote...",
    askSwapGuru: "Uliza Swap Guru",
    swapGuruDesc: "AI inakupata ubadilishanaji bora, haraka na akili.",
    inviteFriend: "Alika rafiki",
    inviteDesc: "Ninyi wote mnapata pointi 50!",
    inviteNow: "Alika Sasa",
    safetyFirst: "Usalama Kwanza",
    safetyDesc: "Kutana mahali pa umma. Thibitisha vitu. Amini jumuiya.",
    safetyTips: "Vidokezo vya Usalama →",
    topTraders: "Wafanyabiashara Bora",
    viewLeaderboard: "Ona Orodha ya Ushindi",
    recentMessages: "Ujumbe wa Hivi Karibuni",
    viewAllMessages: "Ona ujumbe wote →",
    yourActivity: "Shughuli Yako",
    listings: "Orodha",
    active: "Inayoendelea",
    swapsInProgress: "Ubadilishanaji Unaoendelea",
    points: "Pointi",
    viewAllActivity: "Ona shughuli zote →",
    youreIn: "Uko katika",
    changeCampus: "Badilisha Kampasi",
    exploreNear: "Chunguza karibu nawe",
    within5km: "Ndani ya km 5",
    matchScore: "mechi",
    cashBridge: "Daraja la Pesa",
    mpesaTopUp: "Ongeza M-Pesa",
    sendProposal: "Tuma Pendekezo",
    counterOffer: "Jibu la Kupinga",
    accept: "Kubali",
    reject: "Kataa",
    cancel: "Ghairi",
    confirm: "Thibitisha",
    submit: "Wasilisha",
    back: "Rudi",
    next: "Endelea",
    done: "Imekamilika",
    loading: "Inapakia...",
    noResults: "Hakuna matokeo",
    typeMessage: "Andika ujumbe...",
    sendVoiceNote: "Tuma ujumbe wa sauti",
    quickReplies: ["Je, inapatikana?", "Tunaweza kukutana leo?", "Hali yake ni nini?", "Ongeza pesa sawa?"],
    proposalStatus: {
      draft: "Rasimu",
      sent: "Imetumwa",
      viewed: "Imeangaliwa",
      accepted: "Imekubaliwa",
      countered: "Imepingwa",
      rejected: "Imekataliwa",
      completed: "Imekamilika",
      expired: "Imeisha",
      cancelled: "Imeghairiwa",
    },
    swapGuruPrompts: [
      "Ninaweza kupata nini kwa vitabu hivi?",
      "Nipate laptop karibu na JKUAT",
      "Ubadilishanaji bora wa vifaa vya michezo?",
      "Je, biashara hii ni ya haki?",
    ],
    multiWaySwap: "Ubadilishanaji wa Njia Nyingi",
    chainVisualization: "Mnyororo wa Ubadilishanaji",
    confirmLeg: "Thibitisha sehemu hii",
    swapCycle: "Mzunguko wa Ubadilishanaji",
    rateSwap: "Kadiria Ubadilishanaji Huu",
    itemAccuracy: "Usahihi wa Kitu",
    communication: "Mawasiliano",
    punctuality: "Utaratibu wa Wakati",
    fairness: "Uadilifu",
    overallRating: "Tathmini ya Jumla",
    submitReview: "Wasilisha Tathmini",
    reportUser: "Ripoti Mtumiaji",
    savedItems: "Vitu Vilivyohifadhiwa",
    watchlist: "Orodha ya Kuangalia",
    language: "Lugha",
    english: "Kiingereza",
    swahili: "Kiswahili",
    settings: "Mipangilio",
    helpSafety: "Msaada na Usalama",
    logout: "Toka",
    login: "Ingia",
    signup: "Jisajili",
    editProfile: "Hariri Wasifu",
    myListings: "Orodha Zangu",
    mySwaps: "Ubadilishanaji Wangu",
    notifications: "Arifa",
    saved: "Zilizohifadhiwa",
    inviteFriends: "Alika Marafiki",
    superTrader: "Mfanyabiashara Bora",
    pts: "pt",
    km: "km",
    min: "dak",
    ago: "iliyopita",
    new: "MPYA",
    hot: "🔥",
  },
};

type Translations = typeof translations.en;

interface LanguageContextType {
  lang: Lang;
  setLang: (lang: Lang) => void;
  t: Translations;
}

const LanguageContext = createContext<LanguageContextType>({
  lang: "en",
  setLang: () => {},
  t: translations.en,
});

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [lang, setLang] = useState<Lang>("en");
  return (
    <LanguageContext.Provider value={{ lang, setLang, t: translations[lang] }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  return useContext(LanguageContext);
}
